### ISSUE TITLE
Sample File available ?

### ISSUE THREAD

**Issue by K4KDR** [CSUMontpellier/CSUM-GS#1]
Good day!

Thank you for the excellent tools in this repository.

Is there a sample I/Q or AUDIO file available that we can use to test our systems before satellite deployment?

Thanks very much & best of luck with your missions!

-Scott,  K4KDR

**Comment by rafaelmendes** [comment]
Hello,

Yes, can you try the following file? It's a recorded beacon frame from MTCUBE Engineering Model, sampled at 96000 samples/second.

[Mtcube_frame_gmsk2k4_96000rate.zip](https://github.com/CSUMontpellier/CSUM-GS/files/9096640/Mtcube_frame_gmsk2k4_96000rate.zip)

Let me know if it works,
Rafael

**Comment by K4KDR** [comment]
Thank you!   Working on a test immediately.

**Comment by K4KDR** [comment]
Just to confirm, is that .bin file a 32-bit float I/Q, or some other format?

Thank you!

**Comment by rafaelmendes** [comment]
It's complex samples (IQ) recorded using GNURADIO "[File Sink](https://wiki.gnuradio.org/index.php/File_Sink)" block right after an SDR receiver block.

Were you able to decode the frames?

**Comment by K4KDR** [comment]
Thank you - still working on how to utilize that type of file

**Comment by rafaelmendes** [comment]
Take a look at this example. It's based on the script available in the receivers folder of this repository. You can just replace the path to your file in the File Source block and it should work.

[rob1u_gmsk_2400_receiver_from_file.grc.zip](https://github.com/CSUMontpellier/CSUM-GS/files/9096773/rob1u_gmsk_2400_receiver_from_file.grc.zip)

Let me know how it goes.

**Comment by K4KDR** [comment]
That's the one I was using - thanks so much for confirming that.  With no change other than adding a **FILE SOURCE** block & setting the **samp_rate** to 96000, I get:

```
Executing: /usr/bin/python3.6 -u /home/k4kdr/CSUM-GS/receivers/rob1u_gmsk_2400_receiver.py

Traceback (most recent call last):
  File "/home/k4kdr/CSUM-GS/receivers/rob1u_gmsk_2400_receiver.py", line 385, in <module>
    main()
  File "/home/k4kdr/CSUM-GS/receivers/rob1u_gmsk_2400_receiver.py", line 361, in main
    tb = top_block_cls(default_baud=options.default_baud, default_dev=options.default_dev, default_freq=options.default_freq)
  File "/home/k4kdr/CSUM-GS/receivers/rob1u_gmsk_2400_receiver.py", line 182, in __init__
    self.fir_filter_xxx_0_0 = filter.fir_filter_fff(sps_dec_factor, low_pass_taps_2)
  File "/usr/local/lib/python3/dist-packages/gnuradio/filter/filter_swig.py", line 6445, in make
    return _filter_swig.fir_filter_fff_make(decimation, taps)
RuntimeError: block::set_relative_rate: decimation rate cannot be 0
```

**Comment by K4KDR** [comment]
... and of course disabled the 'GPredict Doppler' block.

**Comment by rafaelmendes** [comment]
Ah just to be sure, you need to add your File Source after the Xlating filter and you can remove everything before that (Xlating filter + SDR source). I think you are getting this error message because once you set **samp_rate=96000** the sampling rate of the low pass filter becomes invalid.

**Comment by K4KDR** [comment]
Very helpful - thank you!   It seems that a calculated decimation value used farther down is evaluating to zero as well:

![Screenshot from 2022-07-12 21-08-08](https://user-images.githubusercontent.com/19886368/178595869-dde07c81-3af3-445a-94b8-490b81da5298.png)

**Comment by rafaelmendes** [comment]
Indeed... because samp_rate is supposed to be the SDR sampling rate (1.92 Msps) and then decimated by the Xlating filter to 96000 sps. I think that if you just leave **samp_rate=1.92Msps**, everything should work well because then **samp_rate_dec** will be 96ksps which matches the sampling rate of your file. 

Also, don't forget to add a throttle block (at 96000) to limit CPU usage.

**Comment by K4KDR** [comment]
Excellent - thanks once again for your help & guidance.    That produces a proper packet, so I'll use this modified flowgraph to produce an audio file that I can use with other flowgraphs & other tools that the community normally uses to do further testing.  The altitude of these satellites is going to be a challenge, but we're all willing to try!   Of course please let me know if I can do anything to assist (ditto anyone & everyone you might reach through social media from the Amateur Community)

```
* MESSAGE DEBUG PRINT PDU VERBOSE *
()
pdu_length = 252
contents = 
0000: 8c 68 96 94 b0 40 e0 8c b0 6c 8c a4 82 e1 03 f0 
0010: ea 10 6e 52 4a 5c f9 51 4a 5c 00 00 02 33 78 b0 
0020: 02 00 42 00 ad 00 44 a8 55 a8 bb b4 00 00 81 0e 
0030: 08 3c 34 00 00 00 22 10 00 11 00 00 04 00 f6 0e 
0040: 00 64 20 00 00 1d 51 04 ff 07 80 00 80 00 40 00 
0050: 05 04 ff 07 e0 00 c0 00 1e 00 00 00 00 00 00 00 
0060: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
0070: 00 00 00 00 03 00 00 52 4f 42 55 53 54 41 2d 31 
0080: 55 20 46 58 36 46 52 41 00 00 00 00 00 00 00 00 
0090: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00f0: 00 00 00 00 00 00 00 00 00 00 00 00 
***********************************
```
