### ISSUE TITLE
Contact email address not valid

### ISSUE THREAD

**Issue by K4KDR** [CSUMontpellier/CSUM-GS#2]
Attempted to email the address listed in "
Decoding_MTCUBE2_and_CELESTA_Mission_and_Hamradio_challenge_v1_0.pdf" but it is apparently not a valid email address:

`Your message wasn't delivered to csu-radioham-contact@umontpellier.fr because the address couldn't be found, or is unable to receive mail.`

Thank you!

-Scott,  K4KDR

**Comment by rafaelmendes** [comment]
Hello,

Indeed, there is a typo in the email address of the document. The correct email address is: 
csum-radioham-contact@umontpellier.fr

We will publish a corrected version of the document at https://csum.umontpellier.fr/nanosatellites-projets-ressources/
