### ISSUE TITLE
Telemetry Submit Server:  Online Yet?

### ISSUE THREAD

**Issue by K4KDR** [CSUMontpellier/CSUM-GS#3]
When running a test decode with the 'Telemetry Forwarder' block enabled, I get:

`Error while submitting telemetry: HTTP Error 500: Internal Server Error`

... is perhaps the ability to upload data not enabled yet?   Of course that's understandable, but just wanted to confirm.

Many thanks!

-Scott,  K4KDR

**Comment by rafaelmendes** [comment]
Yes, exactly. It will be enabled tomorrow after launch.

**Comment by K4KDR** [comment]
Thank you!
